// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Key addresses the pull request a branch has. Host decides which forge is
 * asked, because every forge spells owner and repo the same.
 */
export interface Key {
    "host": string;
    "owner": string;
    "repo": string;
    "branch": string;
}

/**
 * PullRequest is a branch's pull request. Everything below Status is
 * meaningful only for StatusFound. The json tags are camelCase because the
 * desktop returns this type to its frontend as is.
 */
export interface PullRequest {
    "status": Status;
    "number": number;
    "title": string;
    "state": string;
    "isDraft": boolean;
    "url": string;

    /**
     * ReviewDecision is GitHub's own vocabulary (APPROVED, CHANGES_REQUESTED,
     * REVIEW_REQUIRED), or empty when review is not required.
     */
    "reviewDecision": string;

    /**
     * Checks is passing, pending, failing, or empty for a head commit with no
     * checks configured.
     */
    "checks": string;

    /**
     * The pull request's own line counts, not the working tree's: those drift
     * as the branch moves on.
     */
    "additions": number;
    "deletions": number;

    /**
     * Cached tells "this just arrived" from "this was already known". The
     * desktop animates only the former.
     */
    "cached": boolean;
}

/**
 * Status is why there is no pull request to show, or that there is one.
 * Rendering "no pull request" for a failed lookup or a disconnected account
 * states a different, wrong fact, so the four stay apart.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusNone = "none",
    StatusFound = "found",
    StatusDisconnected = "disconnected",
    StatusUnsupported = "unsupported",
};
