// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Key {
    "host": string;
    "owner": string;
    "repo": string;
    "branch": string;
}

/**
 * PullRequest fields below Status are set only for StatusFound. The json tags
 * are camelCase because the desktop returns this type to its frontend as is.
 */
export interface PullRequest {
    "status": Status;
    "number": number;
    "title": string;
    "state": string;
    "isDraft": boolean;
    "url": string;

    /**
     * ReviewDecision is APPROVED, CHANGES_REQUESTED, REVIEW_REQUIRED, or empty.
     */
    "reviewDecision": string;

    /**
     * Checks is passing, pending, failing, or empty when no checks run.
     */
    "checks": string;
    "additions": number;
    "deletions": number;

    /**
     * Cached is true when the answer came from the cache. The desktop animates
     * only a fresh one.
     */
    "cached": boolean;
}

/**
 * Status keeps "no pull request" apart from a disconnected account and an
 * unsupported host, which state different facts.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusNone = "none",
    StatusFound = "found",
    StatusDisconnected = "disconnected",
    StatusUnsupported = "unsupported",
};
